#see: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#server.context-path=/zk-spring-boot
#server.port=8080

zk:
  springboot-packaging: jar
  homepage: home

logging.level:
  root: INFO
  org.jumin: DEBUG